# Generated by Django 3.0.6 on 2020-07-30 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='d', max_length=20, null=True)),
                ('city_address_of_bookstore', models.CharField(max_length=20)),
                ('specific_address', models.TextField()),
                ('bookstore_information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation_about_bookstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.IntegerField(default=0)),
                ('comment_about_bookstore_with_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('traits', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookstore_image', models.ImageField(blank=True, upload_to='image')),
                ('bookstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongnaechekbang.Bookstore')),
            ],
        ),
        migrations.CreateModel(
            name='Bookstore_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('event_date', models.DateField(auto_now=True)),
                ('bookstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongnaechekbang.Bookstore')),
            ],
        ),
        migrations.AddField(
            model_name='bookstore',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongnaechekbang.Trait'),
        ),
    ]
