# Generated by Django 3.0.7 on 2020-07-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('city', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='trait',
            fields=[
                ('traits', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='bookstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('specific_address', models.TextField()),
                ('bookstore_information', models.TextField()),
                ('city_address_of_bookstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongnaechekbang.city')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongnaechekbang.trait')),
            ],
        ),
    ]
