# Generated by Django 3.0.6 on 2020-07-25 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('city_address_of_bookstore', models.TextField()),
                ('specific_address', models.TextField()),
                ('bookstore_information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='trait',
            fields=[
                ('traits', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='informations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookstore_image', models.ImageField(blank=True, upload_to='image')),
                ('bookstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongnaechekbang.bookstore')),
            ],
        ),
        migrations.CreateModel(
            name='bookstore_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('event_date', models.DateField(auto_now=True)),
                ('bookstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongnaechekbang.bookstore')),
            ],
        ),
        migrations.AddField(
            model_name='bookstore',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongnaechekbang.trait'),
        ),
    ]
