# Generated by Django 3.0.7 on 2020-07-31 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dongnaechekbang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='informations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookstore_image', models.ImageField(blank=True, upload_to='image')),
                ('bookstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongnaechekbang.bookstore')),
            ],
        ),
    ]
