# Generated by Django 3.0.6 on 2020-07-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongnaechekbang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='bookstore_image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
