# Generated by Django 3.0.6 on 2020-07-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dongnaechekbang', '0002_auto_20200726_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='city_address_of_bookstore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongnaechekbang.City'),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongnaechekbang.Trait'),
        ),
        migrations.AlterField(
            model_name='bookstore_event',
            name='bookstore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongnaechekbang.Bookstore'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='bookstore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dongnaechekbang.Bookstore'),
        ),
    ]
