# Generated by Django 3.0.7 on 2020-07-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongnaechekbang', '0002_informations'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='bookstore_image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.DeleteModel(
            name='informations',
        ),
    ]
