# Generated by Django 3.0.6 on 2020-07-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongnaechekbang', '0004_auto_20200731_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
