# Generated by Django 3.0.6 on 2020-07-31 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dongnaechekbang', '0005_blog_hit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
